BikeIndex/BikeIndex.entitlements
- Add webcredentials:bikeindex.org to associated-domains for credential authorization with bikeindex.org
- This allows easier and faster authentication for users who have a password manager storing credentials for the matched domain
- Documentation for webcredentials: https://developer.apple.com/documentation/xcode/supporting-associated-domains
- Requires bikeindex.org/.well-known/apple-app-site-association to contain the appropriate concatenated app ID prefix and bundle ID in PR https://github.com/bikeindex/bike_index/pull/2586
=> Add associated-domains for web credentials on the bikeindex.org domain

BikeIndex.xcodeproj/project.pbxproj, BikeIndex.xcodeproj/xcshareddata/xcschemes/Debug (bikeindex.org).xcscheme, BikeIndex.xcodeproj/xcshareddata/xcschemes/Debug (development).xcscheme, BikeIndex/Model/User.swift, BikeIndex/View/MainContent/ContentView.swift, BikeIndex/View/Registering/ManufacturerEntryView.swift, BikeIndex/View/Registering/RegisterBikeView.swift, BikeIndex/View/Settings/AcknowledgementsListView.swift, BikeIndex/View/TextLink.swift, BikeIndex/View/Web/NavigatorChild.swift
- Fix warnings from project built with Xcode Version 16.0 (16A242d).
- Clean up some minor comments
- Note: these changes **do not** correct Swift 6 Strict Concurrency Checking warnings. That will be addressed separately.
=> Fix Xcode 16 warnings

.github/workflows/ios.yml, Brewfile, Brewfile.lock.json, README.md, fastlane/Fastfile
- Add basic GitHub Actions to run fastlane tests on `main` branch and pull request branches
- Add CI build status to README.md 😇 
1. Using Xcode 16
2. Uses development API token for bikeindex.org
3. Running on iPhone 16, iPhone 16 Plus, and iPad (10th generation) all running iOS 18.
4. Runs full test suite and writes output to GitHub Actions artifacts
=> Add basic GitHub Actions project setup

BikeIndex.xcodeproj/project.pbxproj, BikeIndex/View/Registering/ManufacturerEntryView.swift, BikeIndexTests/ManufacturerTests.swift
Correct behavior when writing an `AutocompleteManufacturer` model to perform `modelContext.save()` after an insert.
- There is a `@Attribute(.unique)` constraint on the `identifier: Int` field :)
- But when two models are created in quick succession, and not saved, then the uniqueness constraint is not enforced and the next save will fail :(
| Before | After |
| -- | -- |
| ![Simulator Screen Recording - iPhone 16 Pro - 2024-11-17 at 19 59 17](https://github.com/user-attachments/assets/3cd9b89e-4112-4324-a5cc-a2e82c9899d3) | ![Simulator Screen Recording - iPhone 16 Pro - 2024-11-17 at 19 36 36](https://github.com/user-attachments/assets/b5270db4-55c6-41d5-94ee-0f7411c548c3) |
=> fix: manufacturer uniqueness

BikeIndex/Model/Bike.swift
- Add support for 2026 model-year bikes
=> Fix: Add support for 2026 model bikes

BikeIndex.xcodeproj/project.pbxproj
> There are several benefits to using folders instead of groups when organizing your Xcode project files. Folders have a much smaller representation in the project file, which can result in fewer merge conflicts because when you add or remove files to the project you don’t modify the project file. Additionally, your Xcode project file automatically updates as you make changes to the file system.
-- https://developer.apple.com/documentation/xcode/managing-files-and-folders-in-your-xcode-project#Convert-groups-to-folders
Still using Xcode 16.0 at this time.
=> Fix: Convert Xcode project groups to folders 

BikeIndex/View/MainContent/MainContentPage.swift, BikeIndex/View/Onboarding/AuthView.swift, BikeIndex/View/Settings/AppVersionInfo.swift, BikeIndex/View/Settings/SettingsAttributionCaption.swift, BikeIndex/View/Settings/SettingsPage.swift, BikeIndex/View/TextLink.swift
- Display full app version in Settings (marketing version + build number)
| Before | After |
| -- | -- |
| ![Simulator Screenshot - iPhone 16 - 2025-01-18 at 15 20 49](https://github.com/user-attachments/assets/124bc9f9-565f-4620-befb-e1c969ae27db) | ![Simulator Screenshot - iPhone 16 - 2025-01-18 at 15 20 14](https://github.com/user-attachments/assets/b3d08b11-3e57-404c-8168-755f9e297a9e) |
=> Fix: Display app version in Settings

BikeIndex/View/MainContent/ContentBikeButton.swift, BikeIndexUITests/AuthenticatedUITestCase.swift, BikeIndexUITests/BikeIndexUITests.swift
- Archive builds were failing due to control flow in this `#Preview` macro
- Old implementation succeeds for Debug builds
=> Fix: side-step build failure on Preview macro by removing do-catch

.github/workflows/ios.yml, BikeIndexUITests/AuthenticatedUITestCase.swift, fastlane/Fastfile
- Triage: add check to ensure OAuth message is not present
- Also make sure only one webview is present. Just-in-case.
=> Fix: UI Tests sign-in resilience

BikeIndex/Model/Registering/BikeRegistration.swift
- Remove duplicated code
- Update opt-in for BikeRegistration.test field for `DEBUG` builds **only**.
- Update comments
=> Fix: Strengthen test bike registration

BikeIndex/View/Registering/RegisterBikeView.swift
- Fix navigation error, UI would wrongly remain on registration page.
- Console warning from previous implementation:
> Accessing Environment<DismissAction>'s value outside of being installed on a View. This will always read the default value and will not update.
=> Fix: Bike Registration dismiss action

BikeIndex/View/Settings/SettingsPage.swift
Work-around warning encountered on iOS 18 when signing out:
> The `navigationDestination` modifier only works inside a `NavigationStack` or `NavigationSplitView`. There's a misplaced `navigationDestination(for:destination:)` modifier for type `SettingsSelection`. It will be ignored.
Sign-out works by invoking `Client.destroySession()` which 1) resets the authentication state and 2) causes BikeIndexApp's `body { if client.authenticated }` to render.
=> Fix: pop-to-root during Sign Out to work around warning

BikeIndex/Model/Settings/AcknowledgementPackage.swift, BikeIndex/Utility/URL+ExpressibleByStringLiteral.swift, BikeIndex/View/MainContent/MainContentPage.swift, BikeIndex/View/Settings/AcknowledgementPackageDetailView.swift, BikeIndex/View/Web/NavigableWebView.swift, UnitTests/BikeIndexOrgApiV3Tests.swift
- Inspired by SwiftLee Weekly - Issue 260
- Replace `URL(string:).unsafelyUnwrapped` with `URL(stringLiteral:)` which does not require unwrapping
=> Feat: Replace URL(string:).unsafelyUnwrapped with URL: ExpressibleByStringLiteral

BikeIndex/View/Web/NavigatorChild.swift
- Clean up preconcurrency import now that Swift 6 strict concurrency checking is active
=> Fix: Clean up preconcurrency import

BikeIndex/View/Registering/RegisterBikeView.swift
- Binding.get {} needed to use $bike.serial binding _and then_ retrieve the wrappedValue instead of accessing the string value once directly
- See Binding+Optional.swift for reference (but this instance needs to update the missingSerial field too)
=> Fix: Update RegisterBikeView binding on Bike.serial to update

BikeIndex/View/MainContent/MainContentPage.swift, BikeIndex/View/Registering/RegisterBikeView.swift, BikeIndex/View/TextLink.swift, UITests/BikeIndexUITests.swift
- Replace @Environment(\.dismiss) with NavigationPath.pop() which is stable on iOS 18.2
- 'Serial info' link and "How to get your stolen bike back" links opened an infinite recursion on Environment Dismiss changed on v1.2 beta build
- Fix typos and add documentation
=> Fix: remove dismiss env var from RegisterBikeView to fix nav issues

BikeIndex/Model/Navigation/MainContent.swift, BikeIndex/View/MainContent/MainContentPage.swift, BikeIndex/View/MainContent/MainToolbar.swift, BikeIndex/View/Onboarding/AuthView.swift, BikeIndex/View/SearchBikesView.swift, BikeIndex/View/Settings/AcknowledgementPackageDetailView.swift, BikeIndex/View/TextLink.swift, BikeIndex/ViewModel/Onboarding/AuthViewModel.swift, UITests/BikeIndexUITests.swift
- Add 📘 `book.closed` Help item to AuthView and MainContentPage toolbars.
- Replace unused `SearchBikesView` with an actual implementation (to fix `URL(stringLiteral:)` usage inside Previews).
- Remove unused native-search state management from MainToolbar.
- Add `BikeIndexLink.help`.
- Add UI test to ensure Help button is tappable, opens, and then back button works.
| Before - main content | After - main content |
| -- | -- |
| ![Simulator Screenshot - iPhone 16 - 2025-03-29 at 18 31 57](https://github.com/user-attachments/assets/c39ec5ce-5f2f-44ac-b297-c2b98a9a909d) | ![Simulator Screenshot - iPhone 16 - 2025-03-29 at 18 28 34](https://github.com/user-attachments/assets/2153d3a6-1ce5-461d-a7bb-1948397d367a) |
| Before - auth view | After - auth view |
| -- | -- |
| ![Simulator …
=> Feat: Add Help link

BikeIndex/BikeIndex.entitlements
- Finish connecting universal links for QR stickers
- https://github.com/bikeindex/bike_index_ios/pull/55
- https://github.com/bikeindex/bike_index/pull/2756
- Guide: https://developer.apple.com/documentation/xcode/supporting-associated-domains
=> Feat: Add applinks entitlement to complete universal links

BikeIndex/BikeIndexApp.swift
- v1.3 cold start launches from QR sticker camera scans worked
- v1.3 subsequent launches (warm start) from camera scans failed, this PR fixes that scenario
=> Fix: Universal Links from the camera when the app is not-launched

BikeIndex/API/API.swift, BikeIndex/View/BikeDetail/BikeDetailView.swift, BikeIndex/View/MainContent/BikesSection.swift, BikeIndex/View/MainContent/MainToolbar.swift, UITests/MainContentUITestCase.swift
- Special thanks to @calebhearth for this feature request
- Add animations to expandable section indicators (not yet sure how to animate the section contents)
- Begin adding accessibility information to BikesSection custom disclosure control
- Add basic UI test for group control
- Fix some typos
| Bikes by manufacturer | Bikes by status |
| -- | -- |
| <img width="454" alt="Screenshot 2025-05-03 at 14 50 21" src="https://github.com/user-attachments/assets/dccfd00d-d7bc-4116-ae56-911c53ab2a00" /> | <img width="443" alt="Screenshot 2025-05-03 at 14 49 47" src="https://github.com/user-attachments/assets/b283a80f-6449-47b7-9c4d-f66cc239f783" /> |
| Demo of UI Test in action |
| -- |
| <video src="https://github.com/user-attachments/assets/aefc783f-3807-43f0-a67a-33ae680272ea"> |
=> Feat: Add expandible sections to MainContentPage

BikeIndex.xcodeproj/project.pbxproj, BikeIndex.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, BikeIndex/View/MainContent/BikesList.swift, BikeIndex/View/MainContent/ContentBikeButton.swift, BikeIndex/View/MainContent/MainContentPage.swift
- Add https://swiftpackageindex.com/lorenzofiamingo/swiftui-cached-async-image package
- Add CachedAsyncImage for BikesList > BikesSection > ContentBikeButton images
- Separate BikesList empty states for clarity
1. App is fetching bikes
2. This user does not have any bike registrations
3. Bikes are available and displayed
- In the future: BikesList should be renamed to BikesVGrid because it wraps ProportionalLazyVGrid
| Previous behavior | Updated behavior |
| -- | -- |
| With blue background glitching in and out | Smooth continuous display for the same image! |
| ![Simulator Screen Recording - iPhone 16 - 2025-05-03 at 15 29 21](https://github.com/user-attachments/assets/e63e8100-6a8e-4f89-bdb4-3db4b29c8e66) | ![Simulator Screen Recording - iPhone 16 - 2025-05-03 at 15 30 …
=> Feat: Add image caching

BikeIndex/Model/Settings/AcknowledgementPackage.swift
- Follow-up to https://github.com/bikeindex/bike_index_ios/pull/66
- Update acknowledgements to add [SwiftUI CachedAsyncImage](https://swiftpackageindex.com/lorenzofiamingo/swiftui-cached-async-image)
=> Fix: Acknowledge SwiftUI CachedAsyncImage package

BikeIndex/Model/Bike.swift, BikeIndex/View/MainContent/BikesList.swift, BikeIndex/View/MainContent/BikesSection.swift, BikeIndex/View/MainContent/MainContentPage.swift, BikeIndex/ViewModel/MainContent/MainContent+GroupMode.swift
- Add Bike.yearString to use String-keypath queries in SwiftData and SectionedQuery
- Add Bike.year updates for MainContentPage #Previews
- Add GroupdMode.byYear and SectionValue.byYear to enable grouping and display of bikes-by-year
| Bikes grouped by year | Grouping control |
| -- | -- |
| <img width="461" alt="Screenshot 2025-05-04 at 11 12 10" src="https://github.com/user-attachments/assets/7e6bf675-8013-4619-8883-2fa1e4a6c0fe" /> | <img width="465" alt="Screenshot 2025-05-04 at 11 12 04" src="https://github.com/user-attachments/assets/050a527a-60cd-47af-92a6-58d395da1f56" /> |
=> Feat: Group bikes by year

BikeIndex/Model/Bike.swift, BikeIndex/Model/BikeStatus.swift, BikeIndex/View/MainContent/BikesList.swift, BikeIndex/View/MainContent/BikesSection.swift, BikeIndex/View/MainContent/MainContentPage.swift
- Change Bike.statusString enum-predicate-workaround to use BikeStatus.displayName to avoid later manipulation
- Clarify fields in BikesList (aka BikesGridContainerView)
- Remove mapping where BikesList/BikesGridContainerView would convert GroupMode values to BikesSection.SectionValue values because:
1. Previously this was used to guard against possibly-nil Bike.status: BikeStatus values but that is a required field
2. Previously this was used to convert the Bike.statusString section query back to a proper BikeStatus and retrieve the display name -- but now this all occurs directly when Bike.statusString is written
3. This also caused BikesSection/BikesGridSectionView to run a second query after the BikesList/BikesGridContainerView had already run a query!
- Remove …
=> Fix: Flatten BikesSection.SectionValue into MainContentPage.ViewModel.GroupMode

BikeIndex/Model/Registering/BikeRegistration+Propulsion.swift, BikeIndex/View/MainContent/BikesGridContainerView.swift, BikeIndex/View/MainContent/BikesGridSectionView.swift, BikeIndex/View/MainContent/MainContentPage.swift, BikeIndex/ViewModel/MainContent/MainContent+GroupMode.swift
- Rename BikesList to BikesGridContainerView
- Rename BikesSection to BikesGridSectionView
- Remove old todo comment
=> Fix: Clean up bikes grid names

BikeIndex/Model/Registering/RegisterMode.swift, BikeIndex/View/Registering/RegisterBikeView.swift, BikeIndex/View/Registering/StolenBikeInfoSectionView.swift, BikeIndex/View/TextLink.swift, UITests/BikeIndexUITests.swift
- Add information link to bikeindex.org/stolen above 'how to get your stolen bike back' FAQ link
- Fix navigation bar title mode for stolen bike registration
| Old | New |
| -- | -- |
| ![simulator_screenshot_CFC28664-BAD3-4EEC-9B06-553442B415F9](https://github.com/user-attachments/assets/90f56114-7d9c-4411-8b21-e9792f20dac7) | ![simulator_screenshot_74669E30-0B62-4AC9-8590-8E40D2A8328A](https://github.com/user-attachments/assets/51f22947-2224-4144-83d6-3477537197e9) |
=> Feat: Add info links to 'Register a stolen bike' page

BikeIndex/BikeIndexApp.swift, BikeIndex/Model/Deeplinks/DeeplinkManager.swift, BikeIndex/Model/Deeplinks/ScannedBike.swift, BikeIndex/View/Deeplinks/ScannedBikePage.swift, BikeIndex/View/Onboarding/AuthSignInView.swift, BikeIndex/ViewModel/ScannedBikesViewModel.swift, UnitTests/AuthInterceptorTests.swift, UnitTests/ScannedBikeModelTests.swift
Part 1
- Add data layer for 10-most-recent bike stickers scanned in the last 2 weeks
- Change ScannedBike from struct to `@Model class`
- Add `ScannedBikesViewModel` to marshal models
- Change deeplink handling to
1. Create only one `DeeplinkManager` instance (previously it would be destroyed and re-created on every scan).
2. Change only the DeeplinkManager.scannedBike` field for a new scan.
- Move `ScannedBike` to its own file
- Add unit test to check both conditions of history window (10 items, within 2 weeks)
Separation of concerns:
- DeeplinkManager only keeps the latest ScannedBike QR sticker in memory
- ScannedBikesViewModel only writes the latest QR sticker (and purges any scans older than 2 weeks or past the 10-most-recent) to SwiftData
Part 2: pull request to add UI for sticker …
=> Feat: Data layer for QR sticker scan history

BikeIndex/BikeIndexApp.swift, BikeIndex/Model/Deeplinks/DeeplinkManager.swift, BikeIndex/Model/Deeplinks/ScannedBike.swift, BikeIndex/View/Deeplinks/RecentlyScannedStickersView.swift, BikeIndex/View/Deeplinks/ScannedBikePage.swift, BikeIndex/View/MainContent/MainContentPage.swift, BikeIndex/View/MainContent/MainToolbar.swift, BikeIndex/ViewModel/MainContent/MainContent+ViewModel.swift, BikeIndex/ViewModel/ScannedBikesViewModel.swift
- use a static regex to match the pretty sticker display that the website does
- if the regex fails, just a regular string will be displayed
- stylize the StickerDisplayLabel
- use the pretty grouped sticker title for web views
- works for guests and authenticated users
- display Recently Scanned Stickers _fullscreen_ for authenticated users, and in a sheet for guests
Scanned Bikes route through:
- BikeIndexApp deeplink closures to handleDeeplink
- to DeeplinkManager.scan
- to ScannedBike.persist
- back to DeeplinkManager.scannedBike property
- out to various Views that change on the state
=> Feat: Add RecentlyScannedStickersView to display recent QR scans

BikeIndex/View/MainContent/MainContentPage.swift, BikeIndex/ViewModel/MainContent/MainContent+ViewModel.swift
- Previously, Text() was not actionable!
- Rely on default behavior of .alert(action: {}) with empty block
- See: https://developer.apple.com/documentation/swiftui/view/alert(ispresented:error:actions:message:)
- Remove computed properties on MainContentPage.ViewModel to ensure bindings work correctly
| Previous behavior | Corrected behavior |
| -- | -- |
| ![Simulator Screenshot - iPhone 16 - 2025-06-11 at 23 11 00](https://github.com/user-attachments/assets/907f8386-0ba9-49da-b5c1-881e7b172e6b) | ![Simulator Screenshot - iPhone 16 - 2025-06-11 at 23 10 45](https://github.com/user-attachments/assets/af824008-088f-406e-a722-e33efc592261) |
=> Fix MainContentPage alert handler

.github/CODEOWNERS, .github/workflows/ios.yml
- Change ios.yml `pull_request` to `pull_request_target`
- This should enable forks to run fairly safely alongside fair security settings
- Future optimization: revert to `pull_request` and change the CI jobs to run under `workflow_run` 
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
- https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
=> Switch to pull_request_target 

.github/workflows/ios.yml
- Pull requests from forks are _not_ running on the new branch
- They're just running on `main`
- see example PR run https://github.com/bikeindex/bike_index_ios/actions/runs/15938274260/job/44962319474?pr=85 > "Print git checkout status" 
- which matched `main` commit 426664c554369d75d6707ea2ece51a2b0013fb5f
- Remove `branches: [ "main" ]` from ios.yml
- Add `ref: ${{ github.ref }}` to Checkout step (`actions/checkout@v4`)
- Specification for .github/workflows > on: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions\#on
=> CI: Remove branch specifier from pull_request_target trigger

.github/workflows/ios.yml
- Fix code scanning alerts ([alert 1](https://github.com/bikeindex/bike_index_ios/security/code-scanning/1),[ alert 2](https://github.com/bikeindex/bike_index_ios/security/code-scanning/2), [alert 3](https://github.com/bikeindex/bike_index_ios/security/code-scanning/3)) that warn of implicit workflow permissions
- https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
=> CI: Add explicit permissions for GHA GITHUB_TOKEN

.github/workflows/ios.yml
- Actual behavior: PRs run CI on a `main` checkout
- Expected behavior: PRs run CI on _the contents of the PR branch to validate the changes_
=> CI: Tryfix distinguish github context values

.github/workflows/ios.yml
- Seems like pull_request runs correctly for PRs inside the repo
- based on this run: https://github.com/bikeindex/bike_index_ios/actions/runs/15947623925/job/44983633871
- from #94 > ci/debug-pr-checkout-2 > pull_request > iPad run
- Seeking other approaches for pull_request_target from PR branches (maybe workflow_run will help)
- This should leave the repo CI in a stable state, with debug info, until we can dig in to adjust the next fork-based PR
=> CI: Remove pull_request_target

UITests/AuthenticatedUITestCase.swift, UITests/BikeDetailRobot.swift, UITests/BikeIndexUITests.swift, UITests/EditBikeRobot.swift, UITests/MainContentRobot/MainContentRobot.swift, UITests/RegisterBikeRobot.swift, UITests/RegisterStolenBikeRobot.swift, UITests/Robot/MainContentRobot.swift, UITests/Robot/Predicate.swift, UITests/Robot/Robot+Authentication.swift, UITests/Robot/Robot.swift, UITests/SettingsRobot/AcknowledgementsRobot.swift, UITests/SettingsRobot/NavigatesBackToSettings.swift, UITests/SettingsRobot/PrivacyPolicyRobot.swift, UITests/SettingsRobot/SettingsRobot.swift, UITests/SettingsRobot/TermsOfServiceRobot.swift, UITests/UniversalLinksRobot.swift, UITests/UniversalLinksUITest.swift, UITests/WebViewRobot.swift
- Implement the next stage of adopting the Robot Pattern for UI testing by applying it to all the tests in BikeIndexUITests.swift.
- This mainly just translates the previous tests to the new pattern.
- But there were some tests that weren't actually waiting for elements to exist, so this fixes those like with the previous Universal Links test adoption PR.
| Example of previous test | Example of new test |
| --- | --- |
| <img width="710" height="828" alt="Screenshot 2025-07-15 at 5 09 45 PM" src="https://github.com/user-attachments/assets/000b7eb6-6470-47fc-ad23-6f0b70df290a" /> | <img width="427" height="355" alt="Screenshot 2025-07-15 at 5 10 59 PM" src="https://github.com/user-attachments/assets/70431c7b-2bb1-4f88-b84b-53e676ee2a0b" /> |
=> Tests: Adopt Robot pattern for BikeIndexUITests

BikeIndex/Model/Authentication/AuthenticatedUserResponse.swift, BikeIndex/Model/Authentication/OAuthToken.swift, BikeIndex/Model/Authentication/Scope.swift, BikeIndex/Model/ResponseModelInstantiable.swift, UnitTests/OAuthTests.swift
- Simplify Scope array `queryItem` function to combine scopes separated by `+`
- A trialing `+` will be rejected by the API so make sure that doesn't happen with unit tests
- Move ResponseModelInstantiable to its own file
- Rewrite OAuthTests in Swift Testing
=> Simplify Scope queryItem joining
