- BikeIndex.xcodeproj/project.pbxproj
- README.md
- Increment app version for next release(!)
- Add to README:
- Latest App Store Version badge
- Public TestFlight beta link
- Sponsorship note
> Docs: increment app version, update README, add TestFlight public beta link

- BikeIndex/Model/Bike.swift
- BikeIndex/Model/Registering/BikeRegistration.swift
- UnitTests/BikeRegistrationTests.swift
- Fix typo in Serial.unknown constant
- Update BikeRegistration tests to use Swift Testing
> Fix: serial unknown typo

- BikeIndex/API/APIEndpoints.swift
- BikeIndex/BikeIndexApp.swift
- BikeIndex/Model/Authentication/AuthenticatedUserResponse.swift
- BikeIndex/Model/Authentication/OAuthToken.swift
- BikeIndex/Model/Registering/BikeRegisteredQuery.swift
- BikeIndex/Model/Registering/BikeRegistration.swift
- BikeIndex/Model/User.swift
- BikeIndex/View/Debug/DebugDataView.swift
- UnitTests/UserRelationshipTests.swift
- Not appropriate to build on legacy Organization model
> Fix: Remove Organization data model and structures

- BikeIndex.xcodeproj/project.pbxproj
- BikeIndex/API/API.swift
- BikeIndex/Model/AlternateIconsModel.swift
- BikeIndex/Model/Settings/AcknowledgementPackage.swift
- BikeIndex/Utility/Binding+Optional.swift
- BikeIndex/Utility/Logger.swift
- BikeIndex/Utility/ProcessInfo+SnapshotPreview.swift
- BikeIndex/View/Debug/DebugDataView.swift
- BikeIndex/View/MainContent/MainContentPage.swift
- BikeIndex/View/Web/WebScripts.swift
- Adopt Swift 6 language mode with complete strict concurrency checking
- Fix build warnings
> Feat: adopt Swift 6 language mode

- BikeIndex/API/API.swift
- Editing failed recently without this change
> Fix: critical fix for editing bikes, corrected post header

- BikeIndex/API/Client.swift
- BikeIndex/View/Settings/SettingsPage.swift
- UnitTests/ClientRefreshTests.swift
- Replace `Client.destroySession() { Task { @MainActor in ... } }`
- with `@MainActor Client` → `destroySession() async { ... }`
> Fix: Improve Client on main actor

- BikeIndex/API/API.swift
- BikeIndex/API/APIError.swift
- BikeIndex/View/Registering/RegisterBikeView.swift
- Fix typos
- Update API.post inline documentation
- Move APIError to its own file
- Add APIErrorMessage type to decode {"error":""} responses when available
| Before | After |
| -- | -- |
| ![Simulator Screenshot - iPhone 16 Plus - 2025-03-22 at 01 44 22](https://github.com/user-attachments/assets/880fd52b-f53f-440c-af6c-4c7f9a75df5b) | ![Simulator Screenshot - iPhone 16 Plus - 2025-03-22 at 01 42 42](https://github.com/user-attachments/assets/a9efece9-edf6-4113-a709-2bb3d06f5a2b) |
> Fix: Add APIError: LocalizedError conformance, parse and display error

- BikeIndex/Model/MainContent/MainContentModel.swift
- BikeIndex/View/MainContent/MainContentPage.swift
- UnitTests/ClientRefreshTests.swift
- UnitTests/ManufacturerTests.swift
- UnitTests/UserRelationshipTests.swift
- Xcode project now has 0 compiler build warnings!
- Improve documentation
> [!NOTE]
> https://knowyourmeme.com/memes/feels-good
> Fix error type warning and tests warnings

- BikeIndex/API/API.swift
This reverts commit aed4db0bb53522d463ac23fb4fbc31694ee467e5.
> Revert 41 "Fix: critical fix for editing bikes, corrected post header"

- BikeIndex.xcodeproj/project.pbxproj
- BikeIndex.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Update SnapshotPreviews to 0.10.22
> Project: Update SnapshotPreviews to v0.10.22+

- BikeIndex/View/Web/AuthNavigationDelegate.swift
- BikeIndex/View/Web/HistoryNavigator.swift
- BikeIndex/View/Web/NavigationResponder.swift
- BikeIndex/ViewModel/Onboarding/AuthViewModel.swift
- Rename NavigatorChild to NavigationResponder
- Rename AuthNavigationDelegate to AuthenticationNavigator
> Fix: rename AuthenticationNavigator

- UITests/BikeIndexUITests.swift
- Add tests to make sure Settings > Manage Account > non-destructive pages work
> Tests: Add Settings > Manage Account UI tests

- UITests/BikeIndexUITests.swift
- UITests/UniversalLinksUITest.swift
> Tests: Update test queried text after registration change

- .github/workflows/ios.yml
- BikeIndex.xcodeproj/project.pbxproj
- BikeIndex/API/Client.swift
- BikeIndex/Utility/Logger.swift
- BikeIndex/View/Settings/SettingsAttributionCaption.swift
- BikeIndex/View/Web/NavigationResponder.swift
- BikeIndex/View/Web/WebScripts.swift
- UITests/BikeIndexUITests.swift
- UITests/UniversalLinksUITest.swift
- Increment version number
- Increment build number
> Release v1.3

- BikeIndex.xcodeproj/project.pbxproj
- Fix bug with QR Stickers #60
- Increment version and build numbers
> Release v1.3.1

- BikeIndex/API/Client.swift
- BikeIndex/Utility/Logger.swift
- BikeIndex/View/Web/WebScripts.swift
> Feat: Restore /donate links to US

- BikeIndex.xcodeproj/project.pbxproj
- Fix crash when adding bike photos from web editor
| Upload |
| -- |
| <img alt="Screenshot 2025-05-11 at 14 52 55" src="https://github.com/user-attachments/assets/c03a2c0f-fcc2-4803-be18-4651f11dac42" width="50%"> |
> Fix: Add camera and photo library usage description for web-based uploads

- BikeIndex/View/Settings/AppVersionInfo.swift
- BikeIndex/View/Web/NavigationResponder.swift
- UnitTests/AppVersionInfoTests.swift
- Add referral_source with app version to /donate URLs
> Feat: Add /donate?referral_source query parameter

- BikeIndex.xcodeproj/project.pbxproj
- BikeIndex/View/MainContent/MainContentPage.swift
- BikeIndex/View/MainContent/MainToolbar.swift
- Turn off Recently Scanned Stickers UI to refine the behavior slightly
- Build 43
> Release: v1.4.1

- README.md
- Pair with https://github.com/bikeindex/bike_index/pull/2899
- This is necessary for deeplinks and OAuth sign-in to work for iOS clients
> Clarify Redirect URI / Callback URL instructions for first time set-up

- BikeIndex.xcodeproj/project.pbxproj
- Increment version number and build number
- First release built with Xcode 26 (RC) SDK
> Release v1.5.1
